name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simple_java:${{ vars.VERSION }}
          build-args: VARIABLE=${{ vars.VERSION }}
  
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - name: Increment patch version
        uses: eriknyk/increment-variable-action@v1.0.0
        with:
          id: version_code
          name: 'VARIABLE'
          token: ${{ secrets.GITHUB_TOKEN }}


